// <auto-generated />
using System;
using HomeFinance.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeFinance.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221208005407_add-table-installments")]
    partial class addtableinstallments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeFinance.Domain.Models.Finances", b =>
                {
                    b.Property<Guid>("FinancesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_finances");

                    b.Property<string>("FinanceName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(70)")
                        .HasColumnName("finances_name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("owner");

                    b.HasKey("FinancesId")
                        .HasName("id_finances");

                    b.ToTable("finances", (string)null);
                });

            modelBuilder.Entity("HomeFinance.Domain.Models.Installments", b =>
                {
                    b.Property<Guid>("InstallmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("dueDate");

                    b.Property<Guid>("FinancesId")
                        .HasColumnType("uuid");

                    b.Property<int>("InstallmentsPaid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installments Paid");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean")
                        .HasColumnName("Paid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal")
                        .HasColumnName("price");

                    b.Property<int>("TotalInstallments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total Installments");

                    b.HasKey("InstallmentId")
                        .HasName("id_installment");

                    b.HasIndex("FinancesId");

                    b.ToTable("installments", (string)null);
                });

            modelBuilder.Entity("HomeFinance.Domain.Models.Installments", b =>
                {
                    b.HasOne("HomeFinance.Domain.Models.Finances", "Finance")
                        .WithMany("Installments")
                        .HasForeignKey("FinancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finance");
                });

            modelBuilder.Entity("HomeFinance.Domain.Models.Finances", b =>
                {
                    b.Navigation("Installments");
                });
#pragma warning restore 612, 618
        }
    }
}
