// <auto-generated />
using System;
using HomeFinance.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeFinance.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230926001307_ajuste-classe-finances")]
    partial class ajusteclassefinances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeFinance.Domain.Models.Finances", b =>
                {
                    b.Property<Guid>("FinancesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_finances");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinanceName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(70)")
                        .HasColumnName("finances_name");

                    b.Property<int?>("InstallmentsPaid")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("QtdInstallments")
                        .HasColumnType("BIGINT")
                        .HasColumnName("qtd_installments");

                    b.HasKey("FinancesId")
                        .HasName("id_finances");

                    b.ToTable("finances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
